-- CAU 1 --
CREATE DATABASE BAITHI
USE BAITHI
SET DATEFORMAT DMY

CREATE TABLE NHACUNGCAP
(
	MANCC char(5) PRIMARY KEY,
	TENNCC varchar(30),
	QUOCGIA varchar(20),
	LOAICC varchar(40)
)

CREATE TABLE DUOCPHAM
(
	MADP char(5) PRIMARY KEY,
	TENDP varchar(40),
	LOAIDP char(10),
	GIA money
)

CREATE TABLE PHIEUNHAP
(	
	SOPN int PRIMARY KEY,
	NGNHAP smalldatetime,
	MANCC char(5) REFERENCES NHACUNGCAP(MANCC),
	LOAINHAP varchar(10)
)

CREATE TABLE CNPT
(
	SOPN int REFERENCES PHIEUNHAP(SOPN),
	MADP char(5) REFERENCES DUOCPHAM(MADP),
	SOLUONG int,
	PRIMARY KEY(SOPN,MADP)
)

-- CAU 2 --
INSERT INTO NHACUNGCAP(MANCC,TENNCC,QUOCGIA,LOAICC) VALUES 
('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen'),
('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai'),
('NCC03', 'Sapharco', 'Singapore', 'Vang lai');
INSERT INTO DUOCPHAM(MADP,TENDP,LOAIDP,GIA) VALUES
('DP01', 'Thuoc ho PH', 'Siro', 120000),
('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', 200000),
('DP03', 'Cotrim', 'Vien sui', 80000);
INSERT INTO PHIEUNHAP(SOPN,NGNHAP,MANCC,LOAINHAP) VALUES
('00001', '22/11/2017', 'NCC01', 'Noi dia'),
('00002', '04/12/2017', 'NCC03', 'Nhap khau'),
('00003', '10/12/2017', 'NCC02', 'Nhap khau')
INSERT INTO CNPT(SOPN,MADP,SOLUONG) VALUES 
('00001', 'DP01', 100),
('00001', 'DP02', 200),
('00003', 'DP03', 543);

-- CAU 3 --
ALTER TABLE DUOCPHAM ADD CHECK (LOAIDP <> 'Siro' OR GIA > 100000);

-- CAU 4 -- 
-- Hiện thực ràng buộc toàn vẹn sau: Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu. (2đ).

-- BANG TAM ANH HUONG
--              THEM    XOA    SUA 
--NHACUNGCAP	  -		 -		+(QUOCGIA)
--PHIEUNHAP		  + 	 -		+(LOAINHAP,MANCC)

CREATE TRIGGER trg_upd_ncc ON NHACUNGCAP
FOR UPDATE
AS IF UPDATE (QUOCGIA)
BEGIN
	IF EXISTS( SELECT * FROM INSERTED I, PHIEUNHAP PN
				WHERE PN.MANCC = I.MANCC AND I.QUOCGIA <> 'VIET NAM' AND PN.LOAINHAP <> 'NHAP KHAU'
			 )
	BEGIN 
		RAISERROR('LOI', 16, 1)
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT('SUA THANH CONG')
	END
END

CREATE TRIGGER trg_ins_phieunhap ON PHIEUNHAP
FOR INSERT
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, NHACUNGCAP NCC 
				WHERE I.MANCC=NCC.MANCC AND NCC.QUOCGIA <> 'VIET NAM' 
				AND I.LOAINHAP <> 'NHAP KHAU')
	BEGIN 
		RAISERROR('LOI', 16, 1)
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT('NHAP THANH CONG')
	END
END

CREATE TRIGGER trg_upd_phieunhap ON PHIEUNHAP
FOR UPDATE
AS IF (UPDATE(LOAINHAP) OR UPDATE(MANCC))
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, NHACUNGCAP NCC 
				WHERE I.MANCC=NCC.MANCC AND NCC.QUOCGIA <> 'VIET NAM' 
				AND I.LOAINHAP <> 'NHAP KHAU')
	BEGIN 
		RAISERROR('LOI', 16, 1)
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT('SUA THANH CONG')
	END
END

--CAU 5
SELECT * 
FROM PHIEUNHAP 
WHERE MONTH(NGNHAP) = 12 AND YEAR(NGNHAP) = 2017
ORDER BY NGNHAP ASC
--CAU 6
SELECT TOP 1 WITH TIES D.MADP, SUM(SOLUONG) AS TONGSOLUONG 
FROM DUOCPHAM D JOIN CNPT C ON D.MADP = C.MADP JOIN PHIEUNHAP P ON P.SOPN = C.SOPN
WHERE YEAR(NGNHAP) = 2017
GROUP BY D.MADP 
ORDER BY TONGSOLUONG DESC
--CAU 7
SELECT LOAIDP 
FROM DUOCPHAM D JOIN CNPT C ON D.MADP=C.MADP 
	JOIN PHIEUNHAP P ON P.SOPN = C.SOPN 
	JOIN NHACUNGCAP N ON N.MANCC = P.MANCC
WHERE N.LOAICC = 'THUONG XUYEN'
EXCEPT
SELECT LOAIDP 
FROM DUOCPHAM D JOIN CNPT C ON D.MADP=C.MADP 
	JOIN PHIEUNHAP P ON P.SOPN = C.SOPN 
	JOIN NHACUNGCAP N ON N.MANCC = P.MANCC
WHERE N.LOAICC = 'VANG LAI'
--CAU 8
SELECT *
FROM NHACUNGCAP N
WHERE NOT EXISTS (
	SELECT *
	FROM DUOCPHAM D
	WHERE GIA > 100000
	AND NOT EXISTS (
		SELECT *
		FROM PHIEUNHAP P JOIN CNPT C ON C.SOPN = P.SOPN
		WHERE YEAR(P.NGNHAP) = 2017
		AND P.MANCC = N.MANCC AND C.MADP = D.MADP
	)
)